In [1]:
%matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("white")
sns.set_context("poster")

In [3]:
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

boston = load_boston()
df = pd.DataFrame(boston.data)
df.head()

0   1     2   3      4      5     6       7   8    9     10      11    12
0  0.00632  18  2.31   0  0.538  6.575  65.2  4.0900   1  296  15.3  396.90  4.98
1  0.02731   0  7.07   0  0.469  6.421  78.9  4.9671   2  242  17.8  396.90  9.14
2  0.02729   0  7.07   0  0.469  7.185  61.1  4.9671   2  242  17.8  392.83  4.03
3  0.03237   0  2.18   0  0.458  6.998  45.8  6.0622   3  222  18.7  394.63  2.94
4  0.06905   0  2.18   0  0.458  7.147  54.2  6.0622   3  222  18.7  396.90  5.33

In [4]:
df.columns=boston.feature_names
df.head()

CRIM  ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO       B  LSTAT
0  0.00632  18   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98
1  0.02731   0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14
2  0.02729   0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03
3  0.03237   0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94
4  0.06905   0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   5.33

In [12]:
print boston.DESCR

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [7]:
scaler = StandardScaler()
X = scaler.fit_transform(df.values)
y = boston.target

In [8]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lm=LinearRegression()
lm.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
lm.coef_

array([-0.92041113,  1.08098058,  0.14296712,  0.68220346, -2.06009246,
        2.67064141,  0.02112063, -3.10444805,  2.65878654, -2.07589814,
       -2.06215593,  0.85664044, -3.74867982])

In [10]:
lml=Lasso()
lml.fit(X,y)
lml.coef_

array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        2.71335334, -0.        , -0.        , -0.        , -0.        ,
       -1.3435484 ,  0.18095537, -3.54338288])

In [13]:
lmr=Ridge()
lmr.fit(X,y)
lmr.coef_

array([-0.91215884,  1.0658758 ,  0.11942614,  0.68558782, -2.03231631,
        2.67922108,  0.01477326, -3.0777265 ,  2.58814315, -2.00973173,
       -2.05390717,  0.85614763, -3.73565106])